PROGS = test-pmu.c
COMMON_SRC += cache-support.S
COMMON_SRC += mini-step.c
COMMON_SRC += staff-full-except.c
COMMON_SRC += full-except-asm.S
COMMON_SRC += test-pmu-asm.S
COMMON_SRC += pt-vm.c
COMMON_SRC += your-mmu-asm.S
COMMON_SRC += mmu.c
COMMON_SRC += mmu-helpers.c
COMMON_SRC += switchto-asm.S
# STAFF_OBJS = staff-switchto-asm.o

# define this if you need to give the device for your pi
TTYUSB = 
BOOTLOADER = my-install


# uncomment if you want it to automatically run.
RUN=1

include $(CS240LX_2024_PATH)/libpi/mk/Makefile.template-fixed
